//Spotify data HARDCODED w/o Spotify endpoint useEffect fetch
var document1Data = {
  "Post Malone": 4,
  "Travis Scott": 1,
  "Isaiah Rashad": 1,
  Zacari: 1,
  "Kendrick Lamar": 19,
  "Kanye West": 10,
  "John Williams": 1,
  "Itzhak Perlman": 1,
  "Boston Symphony Orchestra": 1,
  "Alexandre Desplat": 2,
  "London Symphony Orchestra": 1,
  "Thomas Newman": 1,
  "Mounika.": 29,
  Logic: 49,
  "Big Sean": 3,
  "Twenty One Pilots": 57,
  "Calvin Harris": 1,
  Disciples: 1,
  "Lilly Wood and The Prick": 1,
  "Robin Schulz": 1,
  "R. City": 1,
  "Adam Levine": 1,
  "Idan Raichel": 3,
  "Anat Ben Hamo": 1,
  "Citizen Cope": 5,
  Coldplay: 9,
  "The Weeknd": 1,
  "Cage The Elephant": 3,
  "Kid Cudi": 9,
  "King Chip": 1,
  "Imagine Dragons": 3,
  "Linkin Park": 1,
  "Shlomi Shabat": 6,
  "Yehuda Poliker": 2,
  "Beit Habubot": 1,
  "Gang Starr": 2,
  "Inspectah Deck": 1,
  "A Tribe Called Quest": 2,
  "Liran Danino": 1,
  "Holy Other": 1,
  "DJ Snake": 1,
  "Bipolar Sunshine": 1,
  Snakehips: 1,
  Tinashe: 1,
  "Chance the Rapper": 14,
  Broiler: 1,
  "Caravan Palace": 1,
  "Local Natives": 6,
  "Youngblood Hawke": 2,
  "Charli XCX": 1,
  "Darwin Deez": 2,
  "Tom Odell": 1,
  "Storm Queen": 1,
  "Panic! At The Disco": 2,
  LOLO: 2,
  BANKS: 2,
  "Atlas Genius": 2,
  "Tove Lo": 2,
  "Hippie Sabotage": 1,
  "The Black Keys": 2,
  Smallpools: 1,
  "Twin Shadow": 1,
  "Ben Howard": 2,
  "John Mayer": 7,
  Lune: 1,
  Fink: 6,
  "Agnes Obel": 1,
  "José González": 1,
  "The Head And The Heart": 2,
  Johnnyswim: 1,
  "Two Door Cinema Club": 4,
  "Queens of the Stone Age": 1,
  Paramore: 1,
  "Foo Fighters": 8,
  "Mikky Ekko": 1,
  "Oliver Nelson": 1,
  "Milky Chance": 6,
  Rudimental: 1,
  "John Newman": 1,
  "Alex Clare": 1,
  "Vance Joy": 2,
  "Electric Light Orchestra": 1,
  "The Killers": 1,
  "Athletes in Paris": 1,
  KDrew: 1,
  "Capital Cities": 1,
  "Alexi Murdoch": 1,
  "Boyce Avenue": 1,
  "Seinabo Sey": 2,
  Kygo: 1,
  Housemates: 1,
  Moderat: 1,
  "James Blake": 1,
  "Foster The People": 2,
  Grouplove: 4,
  Fialta: 1,
  "Phantom Planet": 1,
  "Electric Guest": 1,
  "Ben Kweller": 1,
  "Sea Wolf": 1,
  "Gorgon City": 1,
  MNEK: 1,
  "Family of the Year": 1,
  "Glass Animals": 3,
  "Jenny Lewis": 1,
  "Strand of Oaks": 1,
  Vacationer: 1,
  "The Acid": 1,
  BROODS: 1,
  Folk: 1,
  "Sylvan Esso": 1,
  "Big Data": 1,
  Joywave: 1,
  "Matt Nathanson": 1,
  Spoon: 2,
  "Zella Day": 1,
  "The Fratellis": 1,
  "Satellite Stories": 1,
  "Porter Robinson": 1,
  "Urban Cone": 2,
  SBTRKT: 1,
  "Little Dragon": 1,
  "Gareth Emery": 1,
  Krewella: 1,
  Hardwell: 1,
  "W&amp;W": 1,
  "Totally Enormous Extinct Dinosaurs": 1,
  "Eats Everything": 1,
  Keane: 1,
  "Band of Horses": 1,
  EARTHGANG: 2,
  "Fleetwood Mac": 1,
  Houndmouth: 1,
  "Modest Mouse": 1,
  "Jake Bugg": 1,
  "Broken Bells": 1,
  "The Kooks": 1,
  Weezer: 5,
  "The Lumineers": 2,
  "D-Why": 2,
  "Mount Dreams": 2,
  Anatomy: 2,
  "Jeremy Zucker": 2,
  Subtact: 2,
  "Jay Rodger": 2,
  "The Moth &amp; The Flame": 1,
  "Whilk &amp; Misky": 1,
  "Cold War Kids": 2,
  "Red Hot Chili Peppers": 2,
  "Moon Taxi": 1,
  "J. Cole": 15,
  "alt-J": 1,
  "The Neighbourhood": 1,
  "Arctic Monkeys": 4,
  "Wild Party": 1,
  "Coconut Records": 1,
  "Dan Croll": 1,
  Coasts: 1,
  "Peter Bjorn and John": 1,
  "Knox Hamilton": 1,
  Beck: 1,
  "Franz Ferdinand": 1,
  "The Police": 1,
  "Miike Snow": 1,
  "Bombay Bicycle Club": 1,
  "The Rolling Stones": 1,
  "The Strokes": 3,
  Phoenix: 5,
  "George Clinton": 1,
  Thundercat: 1,
  "Pusha T": 2,
  Lorde: 1,
  "Petit Biscuit": 3,
  "Jack Johnson": 1,
  Låpsley: 1,
  "Snoop Dogg": 1,
  "Wiz Khalifa": 1,
  "Bruno Mars": 1,
  "Black Coast": 2,
  "M. Maggie": 2,
  Labrinth: 1,
  M83: 2,
  "Mating Ritual": 1,
  Gossling: 1,
  "Scott Bradlee's Postmodern Jukebox": 1,
  "Haley Reinhart": 1,
  "Dawn Golden": 1,
  "Chris Gavino": 1,
  "Matt Simons": 1,
  "Falco Van Den Aker": 1,
  "Bob Van Ratingen": 1,
  "JR JR": 1,
  "Alex Wiley": 1,
  Hermitude: 1,
  "TAPZ GALLANTINO": 1,
  "Big K.R.I.T.": 1,
  Mataya: 1,
  Toploader: 1,
  blackbear: 1,
  Oasis: 1,
  "Ark &amp; Ocean": 1,
  "American Authors": 1,
  Vindata: 1,
  "Kenzie May": 1,
  "Alabama Shakes": 1,
  "New Beat Fund": 1,
  "Vinyl Pinups": 1,
  Nirvana: 1,
  ODESZA: 5,
  "Madelyn Grant": 2,
  Zyra: 2,
  "Louis The Child": 1,
  "K.Flay": 1,
  "Pink Floyd": 4,
  "Empire of the Sun": 1,
  Ethnix: 1,
  "Childish Gambino": 17,
  "Steve G. Lover III": 1,
  "Jhené Aiko": 1,
  TLC: 1,
  Drake: 4,
  "MC Eiht": 1,
  "Big Lenbo": 1,
  "Lucy Rose": 1,
  Dria: 1,
  "Jesse Boykins III": 1,
  "Young Money": 1,
  "Meek Mill": 1,
  "Chicago Children's Choir": 1,
  "Lil Wayne": 1,
  "2 Chainz": 1,
  Jeremih: 1,
  "Francis and the Lights": 1,
  "Jamila Woods": 1,
  Saba: 1,
  "Justin Bieber": 1,
  Towkio: 1,
  "Knox Fortune": 1,
  "Jay Electronica": 1,
  "My cousin Nicole": 1,
  Future: 1,
  "T-Pain": 1,
  "Kirk Franklin": 1,
  "Eryn Allen Kane": 1,
  Noname: 1,
  "Ty Dolla $ign": 1,
  "Anderson .Paak": 1,
  "BJ The Chicago Kid": 1,
  Raury: 1,
  Common: 1,
  "JAY-Z": 1,
  "The Beatles": 2,
  Soundgarden: 1,
  Lucian: 1,
  "Amber Run": 1,
  KYLE: 1,
  Flume: 2,
  "Moon Holiday": 1,
  Matisyahu: 1,
  "Kill Paris": 1,
  Royal: 1,
  "Intuition &amp; Equalibrum": 1,
  Cherub: 1,
  Møme: 1,
  "Merryn Jeann": 1,
  "Chet Faker": 1,
  "Years &amp; Years": 1,
  "Jenni Potts": 1,
  "Big Wild": 1,
  "k?d": 1,
  RKCB: 1,
  Healy: 1,
  "Nick Leng": 1,
  "Jack Garratt": 4,
  AlunaGeorge: 1,
  "Jai Paul": 1,
  Swell: 1,
  "Beat Connection": 1,
  xxyyxx: 1,
  CloZee: 1,
  "The Barr Brothers": 1,
  "Bon Iver": 3,
  "The Story So Far": 1,
};

var document2Data = {
  "Twenty One Pilots": 11,
  "Rodrigue Milien": 4,
  Beljazz: 1,
  "Kreyol La": 1,
  "Konpa Kreyol": 2,
  Kai: 2,
  "Richard Cavé": 2,
  "Nu-Look": 6,
  "O.T. Genasis": 1,
  "Lil Baby": 1,
  Gunna: 1,
  "Sammy Davis Jr.": 2,
  Oasis: 1,
  "Stevie Nicks": 1,
  "Billy Joel": 3,
  "Bic Runga": 1,
  "Paula Abdul": 1,
  "Paul Anka": 1,
  "Mone Kamishiraishi": 1,
  RADWIMPS: 1,
  moumoon: 1,
  Aerosmith: 1,
  "Sufjan Stevens": 19,
  "My Chemical Romance": 13,
  "The Longshot": 1,
  "Gerard Way": 1,
  Queen: 8,
  "Green Day": 24,
  "The Weeknd": 4,
  "Foxboro Hottubs": 2,
  Nirvana: 3,
  Weezer: 2,
  "Death Cab for Cutie": 1,
  "blink-182": 1,
  "David Bowie": 2,
  "Elton John": 2,
  Radiohead: 2,
  "Panic! At The Disco": 1,
  Petal: 1,
  Sia: 1,
  Rihanna: 1,
  "Kanye West": 1,
  "Paul McCartney": 1,
};

var document3Data = {
  DAY6: 3,
  SEVENTEEN: 6,
  GOT7: 2,
  BIGBANG: 2,
  "G-DRAGON": 1,
  TAEMIN: 1,
  "Stray Kids": 1,
  "NCT 127": 2,
  EXO: 2,
  "EXO-K": 1,
  EXID: 3,
  KARD: 1,
  "SUPER JUNIOR": 1,
  "Leslie Grace": 1,
  "Play-N-Skillz": 1,
  SHINee: 1,
  "GD X TAEYANG": 1,
  "4Minute": 1,
  MOMOLAND: 1,
  "Red Velvet": 5,
  TWICE: 6,
  "I.O.I": 3,
  "Orange Caramel": 2,
  Lovelyz: 1,
  GFRIEND: 1,
  "Girls' Generation": 2,
  SISTAR: 2,
  HyunA: 1,
  "OH MY GIRL": 1,
  MAMAMOO: 1,
  "Block B": 1,
  KARA: 1,
  "EXO-CBX": 1,
  IU: 2,
  HIGH4: 1,
  VIXX: 1,
  PSY: 1,
  "T-ARA": 2,
  "THE BOYZ": 1,
  AOA: 3,
  PRISTIN: 1,
  SUNMI: 1,
  "f(x)": 1,
};

var document4Data = {
  Hammock: 7,
  LNRDCROY: 1,
  "Petit Biscuit": 1,
  "Brian Eno": 2,
  "Jake Chudnow": 1,
  BOP: 1,
  "Carbon Based Lifeforms": 2,
  "Chihei Hatakeyama": 1,
  "Stars Of The Lid": 1,
  "Silver Mt. Zion": 1,
  Air: 1,
  "Good Weather For An Airstrike": 2,
  "James Blake": 1,
  "Bon Iver": 1,
  "Silver Maple": 1,
  Nonkeen: 2,
  "Blonde Redhead": 1,
  "A Winged Victory for the Sullen": 1,
  "Adam Bryanbaum Wiltzie": 1,
  "Dustin O'Halloran": 1,
  "Keaton Henson": 1,
  "Ren Ford": 1,
  SubtractiveLAD: 1,
  "This Will Destroy You": 1,
  "Calm Shores": 1,
  "Julianna Barwick": 1,
  "Delia Derbyshire Appreciation Society": 1,
  "Marsen Jules": 1,
  Nuages: 1,
  "Ben Frost": 1,
  "Dave Porter": 1,
  "Nil Ciuró": 1,
  Poemme: 1,
  "Village Green": 1,
  "Keith Kenniff": 1,
  Kashuks: 1,
  "Seas of Years": 1,
  "": 1,
  "Hang Drum Player": 1,
  "Chapelier Fou": 1,
  "Clem Leek": 1,
  Moby: 1,
  Helios: 1,
  "Joris Voorn": 1,
  "Aphex Twin": 2,
  Eluvium: 1,
  "Orchid Mantis": 1,
  Loscil: 1,
  Laraaji: 1,
  "Steve Roach": 10,
  "Suspended Memories": 2,
  "Jorge Reyes": 1,
  "Suso Saiz": 1,
  "Philip Glass": 1,
  Nirvana: 10,
  "Blue Chip Orchestra": 2,
  "Jonn Serrie": 2,
  "R. Carlos Nakai": 2,
  "Nawang Khechog": 1,
  "Primeaux & Mike": 1,
  "Joanne Shenandoah": 3,
  "Lawrence Laughing": 1,
  "Coyote Oldman": 2,
  Soulfood: 2,
  "William Eaton": 1,
  "William Clipman": 1,
  "Gary Malkin": 1,
  "Peter Kater": 1,
  "Johnny Whitehorse": 1,
  "Mary Youngblood": 1,
  "AH*NEE*MAH": 1,
  "R. Carlos Nakai, William Eaton": 1,
  "John Huling": 1,
  "Peter Kater, R. Carlos Nakai": 1,
  "Kevin Braheny": 5,
  "Robert Rich": 7,
  "Michael Stearns": 7,
  "Ron Sunsinger": 1,
  "Mychael Danna": 2,
  "Al Gromer Khan": 2,
  "Paul Avgerinos": 2,
  "Constance Demby": 3,
  "Nik Tyndall": 2,
  Raphael: 2,
  "Giles Reaves": 1,
  "Bill Douglas": 3,
  "Tim Story": 1,
  "Ken Stover": 3,
  "Klaus Schønning": 2,
  "Don Harriss": 2,
  "Gershon Kingsley": 4,
  "Michael Amerlan": 2,
  "Tim Clark": 7,
  "Steve McDonald": 1,
  Shiho: 1,
  Kitaro: 1,
  "Irene Papas": 1,
  Vangelis: 1,
  "Thomas de Hartmann": 1,
  Deuter: 1,
  "Paul Lloyd Warner": 1,
  "Steven Kindler": 1,
  "Charles Lloyd": 1,
  "David Darling": 1,
  "Garry Hughes": 3,
  "Layne Redmond": 2,
  "Tommy Brunjes": 1,
  "Mickey Hart": 1,
  "Hamza El Din": 1,
  "Steve Douglas": 1,
  "Shabda Khan": 1,
  "John Doan": 1,
};

var doc1top10 = Object.entries(document1Data) // create Array of Arrays with [key, value]
  .sort(([, a], [, b]) => b - a) // sort by value, descending (b-a)
  .slice(0, 10) // return only the first 10 elements of the intermediate result
  .map(([n]) => n); // and map that to an array with only the name

var doc2top10 = Object.entries(document2Data) // create Array of Arrays with [key, value]
  .sort(([, a], [, b]) => b - a) // sort by value, descending (b-a)
  .slice(0, 10) // return only the first 10 elements of the intermediate result
  .map(([n]) => n); // and map that to an array with only the name

var doc3top10 = Object.entries(document3Data) // create Array of Arrays with [key, value]
  .sort(([, a], [, b]) => b - a) // sort by value, descending (b-a)
  .slice(0, 10) // return only the first 10 elements of the intermediate result
  .map(([n]) => n); // and map that to an array with only the name

var doc4top10 = Object.entries(document4Data) // create Array of Arrays with [key, value]
  .sort(([, a], [, b]) => b - a) // sort by value, descending (b-a)
  .slice(0, 10) // return only the first 10 elements of the intermediate result
  .map(([n]) => n); // and map that to an array with only the name

export { doc1top10, doc2top10, doc3top10, doc4top10 };
